---
title: "R Notebook"
output: html_notebook
---

Aesthetics
```{r, warning=FALSE}

rm(list = ls())

call_aesthethics <- function(text_size){
  
  th <- theme(   panel.grid.major = element_blank(),
                 panel.grid.minor = element_blank(),
                 panel.border = element_blank(),
                 panel.background = element_blank(),
                 axis.line = element_line(size = 0.5), 
                 legend.position = 'right', 
                 legend.text = element_text(size= text_size, family="Helvetica"),
                 text = element_text(size= text_size, family="Helvetica"), 
                 strip.text.x = element_text(size = rel(0.90)), 
                 strip.text.y = element_text(size = rel(0.90)), 
                 axis.title.x = element_text(vjust=-0.3), 
                 plot.title = element_text(hjust = 0.5, vjust = 0), 
                 axis.ticks = element_line(size = 0.4), 
                 axis.text.x.bottom  = element_text(size = rel(0.90), margin = unit(c(t = 2.5, r = 0, b = 0, l = 0), "mm")),
                 axis.title.y = element_text(vjust = 1),
                 axis.text.y = element_text(size = rel(0.90), margin = unit(c(t = 0, r = 2.5, b = 0, l = 0), "mm")),
                 axis.ticks.length = unit(-1.2, "mm"),
                 axis.text.x.top = element_text(size = rel(0.90), margin = unit(c(t = 0, r = 0, b = 2.5, l = 0), "mm")))
  
  return(th)
}


my.colors <-  c('darkred', "#006600", "#800080")
my.colors2 <-  c("#006600", "#800080", "#FF9900", 'deepskyblue4')

```

Libraries
```{r}

library(plyr)
library(lmerTest)
library(dplyr)
library(tidyverse)
library(ggplot2)
library(pracma)
library(plotrix)
library(lemon)
library(car)
library(sjstats)
library(emmeans)
library(lsr)
library(ggpubr)

text_size <- 14
num.tar <- 3
hand_angle_cutoff <- 90
th <- call_aesthethics(text_size)


```

Load Exp 1 Data
```{r}

exp1.report.data <- read.table('/Users/jonathantsay/Library/CloudStorage/Dropbox/Physical Intelligence Lab/Data/zzz_unsorted/Archieved/clampreport/Exp1_Data/report_cluster.csv', header=TRUE, sep=",") %>%
  mutate(cond = report) %>%
  group_by(SN, CN) %>% 
  summarise(cond = mean(cond)) %>%
  group_by(CN) %>% 
  summarise(grp_mean = mean(cond, na.rm = TRUE), 
            grp_sd = std.error(cond, na.rm = TRUE))

exp1.hand.data <- read.table('/Users/jonathantsay/Library/CloudStorage/Dropbox/Physical Intelligence Lab/Data/zzz_unsorted/Archieved/clampreport/Exp1_Data/report_cluster.csv', header=TRUE, sep=",") %>%
  mutate(cond = hand) %>%
  group_by(SN, CN) %>% 
  summarise(cond = mean(cond)) %>%
  group_by(CN) %>% 
  summarise(grp_mean = mean(cond, na.rm = TRUE), 
            grp_sd = std.error(cond, na.rm = TRUE))

exp1.all.data <- cbind(exp1.hand.data[,c('CN', 'grp_mean', 'grp_sd')], exp1.report.data[, c('grp_mean', 'grp_sd')])
names(exp1.all.data) <- c('CN', 'prop_fb', 'prob_fb_sd', 'felt_hand', 'felt_hand_sd')

exp1.all.data <- exp1.all.data[1:70, ]

```

```{r}

clamp_hr_plot <- exp1.all.data %>% 
  mutate(CN = CN - 5) %>% 
  ggplot() + 
  geom_hline(yintercept = c(0), color = 'lightgrey') +
  geom_vline(xintercept = c(0, 0, 20.5), color = 'lightgrey') +
  geom_line(aes(x = CN, y = prop_fb), color = my.colors2[1]) + 
  geom_line(aes(x = CN, y = felt_hand), color = my.colors2[3]) + 
  geom_ribbon(aes(x = CN, ymin = prop_fb - prob_fb_sd, ymax = prop_fb + prob_fb_sd), alpha = 0.25, fill = my.colors2[1]) +
  geom_ribbon(aes(x = CN, ymin = felt_hand - felt_hand_sd, ymax = felt_hand + felt_hand_sd), alpha = 0.25, fill = my.colors2[3]) +
  th +
  labs(y = "Hand Angle (°)", x = 'Movement Cycle (4 Reaches)') 
print(clamp_hr_plot)

setwd("~/Desktop")
ggsave("HR_plot.pdf",
       plot = clamp_hr_plot, height = 3, width = 4,  units = "in")


```


```{r}


e1.handparm <- read.table('~/Dropbox/VICE/JT/UNIFYING_THEORY/Data/Parvin_2020/e1fig/e1_handparam.csv', header=TRUE, sep=",")

af.pv.cor.all.ang <- e1.handparm %>% 
  ggplot(aes(x = PBvarall_ang, y = AEall)) +
  geom_smooth(method = 'lm', formula = 'y~x', color = 'black', alpha = 0.2) + 
  geom_point(color = 'black', size = 2, alpha = 1) + 
  ggpubr::stat_cor(method = 'pearson', aes(x = PBvarall_ang, y = AEall), size = 6) + 
  labs(x = 'Proprioceptive Uncertainty (°)', y = 'Hand Angle (°)') + 
  coord_capped_cart() +
  th
print(af.pv.cor.all.ang)

setwd("~/Desktop")
ggsave("PV_plot.pdf",
       plot = af.pv.cor.all.ang, height = 3, width = 4,  units = "in")

```

```{r}

tj.handparm <- read.table('/Users/jonathantsay/Desktop/TargetJump.csv', header=TRUE, sep=",")

tj.handparm$Cond <- factor(tj.handparm$Cond, levels = c("Standard", "Flash"))

tj.plot <- tj.handparm %>% 
  ggplot(aes(x = Cond, y = Adapt, group = Clamp, color = factor(Clamp))) + 
  geom_pointrange(aes(ymin = Adapt - SEM, ymax = Adapt + SEM)) + 
  geom_line() + 
  th + theme(legend.position = "none") + 
  labs( x= "", y = expression(Delta ~ "Hand Angle (°)")) + 
  scale_color_manual(values = my.colors2[c(1, 2)]) +
  coord_capped_cart(ylim = c(0, 2))
print(tj.plot)

setwd("~/Desktop")
ggsave("tj_plot.pdf",
       plot = tj.plot, height = 3, width = 3,  units = "in")

```
```{r}

rel.handparm <- read.table('/Users/jonathantsay/Desktop/Relevance.csv', header=TRUE, sep=",")

rel.handparm$Cond <- factor(rel.handparm$Cond, levels = c("Relevant", "Irrelevant"))

rel.plot <- rel.handparm %>% 
  mutate(Cond_2 = 1) %>%
  ggplot(aes(x = Cond, y = Hand, group = Cond_2)) + 
  geom_pointrange(aes(ymin = Hand - SD, ymax = Hand + SD)) + 
  geom_line() + 
  th + theme(legend.position = "none") + 
  labs( x= "", y = "Hand Angles!!!!! (°)") + 
  coord_capped_cart(ylim = c(0, 15))
print(rel.plot)

setwd("~/Desktop")
ggsave("rel_plot.pdf",
       plot = rel.plot, height = 3, width = 3,  units = "in")

```
```{r}

mydf <- data.frame(cond = c("Young", "Old", "Young", "Old"), 
                   cond2 = c("Prop", "Prop", "Pred", "Pred"), 
                   values = c(3, 6, 3, 3.5))

mydf$cond <- factor(mydf$cond, levels = c("Young", "Old"))
mydf$cond2 <- factor(mydf$cond2, levels = c("Prop", "Pred"))
                    
mybarplot <- mydf %>% 
  ggplot(aes(x = cond2, y = values, group = cond, color = cond)) +
  geom_point(size = 2) + 
  geom_line() + 
  labs(x = "", y = "Uncertainty (°)") + 
  scale_fill_manual(values = c("black", my.colors2[3], my.colors2[2])) +  
  scale_y_continuous(breaks = c(0, 4, 8), limits = c(0, 8)) +
  th +
  scale_color_manual(values = my.colors2[c(1, 2)]) + 
  theme(legend.position = "none")
print(mybarplot)

setwd("~/Desktop")
ggsave("myage_plot.pdf", plot = mybarplot, height = 3, width = 2, units = "in")

```

```{r}

source("~/Dropbox/VICE/JT/UNIFYING_THEORY/Analysis/unifying_functions.R")
library(purrr)

#important param
my_lamda <- 0
my_satshift <- 10
my_pred_sd <- c(6.54)
my_visfb_sd <- c(6.43)
my_propfb_sd <- c(5, 10)
my_visfb <- c(-15)
my_shift_speed <- 0
my_seen_cursor <- 0
my_felt_hand <- 0
my_forgetting <- c(1)

#secondary param
my_pred_loc <- 0
my_prop_bias <- c(0)
my_visbias <- 0
my_calibration_sd <- 0
my_learning_rate <- 1
my_shift_ratio <- 1
my_output <- 1

my_trial_schedule <- c(rep(1, 10), rep(2, 50))

my_params <- setNames ( expand.grid(my_visfb, 
                                    my_pred_loc, my_pred_sd, my_prop_bias, 
                                    my_propfb_sd, my_visbias, my_visfb_sd, my_lamda, my_satshift, 
                                    my_felt_hand, my_seen_cursor, my_shift_speed, my_calibration_sd, my_learning_rate, 
                                    my_forgetting, my_shift_ratio), 
                        c("my_visfb", "my_pred_loc", "my_pred_sd", "my_prop_bias", 
                          "my_propfb_sd", "my_visbias", "my_visfb_sd", "my_lamda", "my_satshift", 
                          "my_felt_hand", "my_seen_cursor", "my_shift_speed", "my_calibration_sd", "my_learning_rate", 
                          "my_forgetting", "my_shift_ratio"))

all_learn <- data.frame()

for(ti in 1:nrow(my_params)){
  
  my_vis_schedule <- my_trial_schedule
  my_vis_schedule[my_trial_schedule == 2] <- my_params$my_visfb[ti]
  
  all_learn <- rbind(all_learn, cbind(sim_learn(my_trial_schedule, my_vis_schedule, 
                                                my_params$my_pred_loc[ti], my_params$my_pred_sd[ti], my_params$my_prop_bias[ti], 
                                                my_params$my_propfb_sd[ti], my_params$my_visbias[ti],my_params$my_visfb_sd[ti], 
                                                my_params$my_lamda[ti], my_params$my_satshift[ti], my_params$my_felt_hand[ti],
                                                my_params$my_seen_cursor[ti], 
                                                my_params$my_shift_speed[ti], 
                                                my_params$my_calibration_sd[ti], 
                                                my_params$my_learning_rate[ti], 
                                                my_params$my_forgetting[ti],
                                                my_params$my_shift_ratio[ti], 
                                                my_output), 
                                      rep(ti, length(my_trial_schedule))))
  
}



sim_cd <- all_learn %>% 
  mutate(iter = `rep(ti, length(my_trial_schedule))`) %>% 
  gather(cond, value, c("prop_fb", "visseg", "propseg", "felt_hand", "seen_cursor", 'prop_shift', 'vis_shift')) %>%
  drop_na() %>% 
  filter(cond %in% c("prop_fb")) %>%
  ggplot(aes(x = TN, y = value, group = interaction(cond,  iter, my_visfb, pred_sd), color = factor(propfb_sd))) + 
  geom_line(size = 0.75) + 
  scale_y_continuous(breaks = seq(0, 40, 10), limits = c(-1, 40)) +
  labs(x = 'Movement Cycle (4 Reaches)', y = 'Hand Angle (°)', color = ' ') +
  scale_color_manual(values = my.colors2[c(1, 2)]) +
  th +
  theme(legend.position = 'none') 
print(sim_cd)

setwd("~/Desktop")
ggsave("PropSD_plot.pdf",
       plot = sim_cd, height = 3, width = 3.1,  units = "in")


felt_hand_plot <- all_learn %>% 
  mutate(iter = `rep(ti, length(my_trial_schedule))`) %>% 
  gather(cond, value, c("prop_fb", "visseg", "propseg", "felt_hand", "seen_cursor", 'prop_shift', 'vis_shift')) %>%
  drop_na() %>% 
  filter(cond %in% c("felt_hand")) %>%
  ggplot(aes(x = TN, y = value, group = interaction(cond,  iter, my_visfb, pred_sd), color = factor(propfb_sd))) + 
  geom_line(size = 0.75) + 
  scale_y_continuous(breaks = seq(-10, 5, 5), limits = c(-10, 5)) +
  labs(x = 'Movement Cycle (4 Reaches)', y = 'Perceptual Report (°)', color = ' ') +
  scale_color_manual(values = my.colors2[c(1, 2)]) +
  th +
  theme(legend.position = 'none') 
print(felt_hand_plot)

setwd("~/Desktop")
ggsave("FeltHandPropSD_plot.pdf",
       plot = felt_hand_plot, height = 3, width = 3.1,  units = "in")

```
```{r}

mydf2 <- data.frame(cond = c("Sham", "Sham", "Sham", "Stim", "Stim", "Stim"), 
                   cond2 = c("Early", "Mid", "Late","Early", "Mid", "Late"), 
                   values = c(1, 1, 1, 1.2, 1.4, 1.6))

mydf2$cond <- factor(mydf2$cond, levels = c("Sham", "Stim"))
mydf2$cond2 <- factor(mydf2$cond2, levels = c("Early", "Mid", "Late"))
                    
mytimingplot <- mydf2 %>% 
  ggplot(aes(x = cond2, y = values, group = cond, color = cond)) +
  geom_point(size = 2) + 
  geom_line(size = 0.75) + 
  labs( x= "Vibration Timing", y = expression(Delta ~ "Hand Angle (°)")) + 
  scale_fill_manual(values = c("black", my.colors2[3], my.colors2[2])) +  
  scale_y_continuous(breaks = c(0, 1, 2), limits = c(0, 2)) +
  th +
  scale_color_manual(values = my.colors2[c(1, 2)]) + 
  theme(legend.position = "none")
print(mytimingplot)

setwd("~/Desktop")
ggsave("mytiming_plot.pdf", plot = mytimingplot, height = 3, width = 2, units = "in")

```
```{r}

control <- dbeta(seq(0, 1, length = 100), shape1 = 7, shape2 = 3) 

# Min-max normalization
min_control <- min(control)
max_control <- max(control)
normalized_control <- (control - min_control + 1) / (max_control - min_control)
normalized_control <- normalized_control + 0.65

# patient <- normalized_control * 0.5 
patient <- dbeta(seq(0, 1, length = 100), shape1 = 5, shape2 = 15)
min_patient <- min(patient)
max_patient <- max(patient)
normalized_patient <- (patient - min_patient) / (max_patient - min_patient)
normalized_patient <- rep(1, length(normalized_patient))

mydf7 <- data.frame(cond = rep(c("C", "P"), each = 100), 
                    timing = c(seq(0, 1, length = 100), seq(0, 1, length = 100) ) ,
                    values = c( normalized_control, normalized_patient ) )


mydotplot <- mydf7 %>% 
  ggplot(aes(x = timing, y = values, group = cond, color = cond)) + 
  geom_line(size = 0.75) + 
  labs(x = "Feedback Time (a.u.)", y = expression(Delta ~ "Hand Angle (°)")) + #
  scale_y_continuous(breaks = c(0,  2), limits = c(0, 2.2)) +
  scale_x_continuous(breaks = c(0,  1)) +
  scale_color_manual(values =  my.colors2[c(2, 1)]) +
  th +
  theme(legend.position = "none")
print(mydotplot)


setwd("~/Desktop")
ggsave("mytimingdotplot2.pdf", plot = mydotplot, height = 3, width = 3.1, units = "in")

```





```{r}
source("~/Dropbox/VICE/JT/UNIFYING_THEORY/Analysis/unifying_functions.R")

#important param
my_lamda <- 0
my_satshift <- 10
my_pred_sd <- c(3.5, 5, 10)
my_visfb_sd <- c(6.43)
my_propfb_sd <- c(5)
my_visfb <- c(-15)
my_shift_speed <- 0
my_seen_cursor <- 0
my_felt_hand <- 0
my_forgetting <- c(1)

#secondary param
my_pred_loc <- 0
my_prop_bias <- c(0)
my_visbias <- 0
my_calibration_sd <- 0
my_learning_rate <- 1
my_shift_ratio <- 1
my_output <- 1

my_trial_schedule <- c(rep(1, 10), rep(2, 50))

my_params <- setNames ( expand.grid(my_visfb, 
                                    my_pred_loc, my_pred_sd, my_prop_bias, 
                                    my_propfb_sd, my_visbias, my_visfb_sd, my_lamda, my_satshift, 
                                    my_felt_hand, my_seen_cursor, my_shift_speed, my_calibration_sd, my_learning_rate, 
                                    my_forgetting, my_shift_ratio), 
                        c("my_visfb", "my_pred_loc", "my_pred_sd", "my_prop_bias", 
                          "my_propfb_sd", "my_visbias", "my_visfb_sd", "my_lamda", "my_satshift", 
                          "my_felt_hand", "my_seen_cursor", "my_shift_speed", "my_calibration_sd", "my_learning_rate", 
                          "my_forgetting", "my_shift_ratio"))

all_learn <- data.frame()

for(ti in 1:nrow(my_params)){
  
  my_vis_schedule <- my_trial_schedule
  my_vis_schedule[my_trial_schedule == 2] <- my_params$my_visfb[ti]
  
  all_learn <- rbind(all_learn, cbind(sim_learn(my_trial_schedule, my_vis_schedule, 
                                                my_params$my_pred_loc[ti], my_params$my_pred_sd[ti], my_params$my_prop_bias[ti], 
                                                my_params$my_propfb_sd[ti], my_params$my_visbias[ti],my_params$my_visfb_sd[ti], 
                                                my_params$my_lamda[ti], my_params$my_satshift[ti], my_params$my_felt_hand[ti],
                                                my_params$my_seen_cursor[ti], 
                                                my_params$my_shift_speed[ti], 
                                                my_params$my_calibration_sd[ti], 
                                                my_params$my_learning_rate[ti], 
                                                my_params$my_forgetting[ti],
                                                my_params$my_shift_ratio[ti], 
                                                my_output), 
                                      rep(ti, length(my_trial_schedule))))
  
}



sim_cd <- all_learn %>% 
  mutate(iter = `rep(ti, length(my_trial_schedule))`) %>% 
  gather(cond, value, c("prop_fb", "visseg", "propseg", "felt_hand", "seen_cursor", 'prop_shift', 'vis_shift')) %>%
  drop_na() %>% 
  filter(cond %in% c("prop_fb")) %>%
  ggplot(aes(x = TN, y = value, group = interaction(cond,  iter, my_visfb, pred_sd), color = factor(pred_sd))) + 
  geom_vline(xintercept = c(10.5), color = "lightgrey") +
  geom_line(size = 0.75) + 
  scale_y_continuous(breaks = seq(0, 40, 10), limits = c(-1, 40)) +
  labs(x = 'Movement Cycle (4 Reaches)', y = 'Hand Angle (°)', color = ' ') +
  scale_color_manual(values = my.colors2[c(2,1, 3)]) +
  th +
  theme(legend.position = 'none') 
print(sim_cd)

setwd("~/Desktop")
ggsave("PredSD_plot.pdf",
       plot = sim_cd, height = 3, width = 3.1,  units = "in")


felt_hand_plot <- all_learn %>% 
  mutate(iter = `rep(ti, length(my_trial_schedule))`) %>% 
  gather(cond, value, c("prop_fb", "visseg", "propseg", "felt_hand", "seen_cursor", 'prop_shift', 'vis_shift')) %>%
  drop_na() %>% 
  filter(cond %in% c("felt_hand")) %>%
  ggplot(aes(x = TN, y = value, group = interaction(cond,  iter, my_visfb, pred_sd), color = factor(pred_sd))) + 
  geom_vline(xintercept = c(10.5), color = "lightgrey") +
  geom_line(size = 0.75) + 
  scale_y_continuous(breaks = seq(-10, 5, 5), limits = c(-10, 5)) +
  labs(x = 'Movement Cycle (4 Reaches)', y = 'Perceptual Report (°)', color = ' ') +
  scale_color_manual(values = my.colors2[c(2, 1, 3)]) +
  th +
  theme(legend.position = 'none') 
print(felt_hand_plot)

setwd("~/Desktop")
ggsave("FeltHandPredSD_plot.pdf",
       plot = felt_hand_plot, height = 3, width = 3.1,  units = "in")
```

```{r}

pd.data <- read.csv("/Users/jonathantsay/Desktop/PDClamp.csv")
cd.data <- read.csv("/Users/jonathantsay/Desktop/CDClamp.csv")


all.data <- rbind(pd.data, cd.data)
all.data$Group[all.data$Group == "OC_PD"] <- "Control"

E1_plot <- all.data %>% 
  ggplot(aes( x = newCN, y = Hand_ind_mean, group = interaction(Group, phase))) + 
  geom_hline(yintercept = 0, color = "lightgrey") +
  geom_vline(xintercept = c(10.5, 160.5), color = "lightgrey") +
  stat_summary(fun = "mean", geom = "line", aes(color = Group), size = 0.5) + 
  stat_summary(fun.data = "mean_se", geom = "ribbon", aes(fill = Group), alpha = 0.2) +
  labs(x = 'Trial #', y = 'Hand Angle (°)', color = ' ', shape = ' ') + 
  scale_color_manual(values = my.colors2[c(1, 2, 3)], guide = FALSE ) +
  scale_fill_manual(values = my.colors2[c(1, 2, 3)] ) +
  scale_y_continuous(breaks = seq(0, 30, 10)) +
  coord_capped_cart(ylim = c(-5, 35)) +
  th +
  theme(legend.position = 'none')
print(E1_plot)

setwd("~/Desktop")
ggsave("PDCD_plot.pdf",
       plot = E1_plot, height = 3, width = 3.1,  units = "in")

```


```{r}

mydf3 <- data.frame(cond = c("Con", "Con", "PD", "PD", "SCA", "SCA"), 
                   cond2 = c("Prop", "Pred", "Prop", "Pred", "Prop", "Pred"), 
                   values = c(3, 3, 6, 3.5, 3.5, 6))

mydf3$cond <- factor(mydf3$cond, levels = c("Con", "PD", "SCA"))
mydf3$cond2 <- factor(mydf3$cond2, levels = c("Prop", "Pred"))
                    
mybarplot3 <- mydf3 %>% 
  ggplot(aes(x = cond2, y = values, group = cond, color = cond)) +
  geom_point(size = 2) + 
  geom_line() + 
  labs(x = "", y = "Uncertainty (°)") + 
  scale_fill_manual(values = c("black", my.colors2[3], my.colors2[2])) +  
  scale_y_continuous(breaks = c(0, 4, 8), limits = c(0, 8)) +
  th +
  scale_color_manual(values = my.colors2[c(1, 2, 3)]) + 
  theme(legend.position = "none")
print(mybarplot3)

setwd("~/Desktop")
ggsave("mySCA_plot.pdf", plot = mybarplot3, height = 3, width = 2, units = "in")

```

